steps:
   - name: 'maven:3-jdk-8'
     entrypoint: 'mvn'
     args: ["package", "-Dmaven.test.skip=true"]
   - name: 'gcr.io/cloud-builders/docker'
     args: ["build", "-t", "gcr.io/$PROJECT_ID/loggenerator", "--build-arg=JAR_FILE=target/*.jar", "."]
#   - name: gcr.io/cloud-builders/docker
#     args: ["push", "gcr.io/$PROJECT_ID/loggenerator:latest"]
   - name: 'gcr.io/cloud-builders/docker'
     entrypoint: 'bash'
     args: ['-c', 'docker login --username=sureshtripini --password=Qwerty@123']
   - name: 'gcr.io/cloud-builders/docker'
     entrypoint: 'bash'
     args: ['-c', 'docker push sureshtripini/loggenerator:latest']
#https://cloud.google.com/build/docs/interacting-with-dockerhub-images
#images: ["gcr.io/$PROJECT_ID/DummyFileGenerator"]

