steps:
   - name: maven:3-jdk-8
     entrypoint: mvn
     args: ["package", "-Dmaven.test.skip=true"]
   - name: gcr.io/cloud-builders/docker
     args: ["build", "-t", "gcr.io/$PROJECT_ID/loggenerator", "--build-arg=JAR_FILE=target/*.jar", "."]
   - name: gcr.io/cloud-builders/docker
     args: ["push", "gcr.io/$PROJECT_ID/loggenerator:latest"]

#images: ["gcr.io/$PROJECT_ID/DummyFileGenerator"]

